import Head from 'next/head'
import Link from 'next/link'

export default function Layout({children,title,currentPage} : any){
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        <header className='bg-stone-500'>
          <nav className='flex flex-row'>
          <div className='py-4 pr-10 my-auto'>
              <a className='px-5' href='/'>
                <span>Home</span>
              </a>
          </div>
          <div className='flex flex-row-reverse flex-1 py-4 pr-10 my-auto'>      
              <a className='px-5'>
                <span>Contact</span>
              </a>
              <a className='px-5' href="/resume">
                <span>Resume</span>
              </a>
              <a className='px-5'>
                <span>Project</span>
              </a>
            </div>
            </nav>
      </header>
      <main>
          {children}
      </main>
      </div>
    )
}