import Head from 'next/head'
import Link from 'next/link'

export default function Layout({children,title,currentPage} : any){
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        <header className='bg-stone-500'>
          <nav className='flex flex-row-reverse my-auto flex-1 pr-10 py-4'>      
              <a className='px-5'>
                <span>Contact</span>
              </a>
              <a className='px-5'>
                    <span>Resume</span>
                  </a>
                  <a className='px-5'>
                    <span>Project</span>
                  </a>
            </nav>
      </header>
      <main>
          {children}
      </main>
      </div>
    )
}